[uwsgi]
chdir = /usr/share/webapps/spano
protocol = uwsgi

# this requires modifications from our fork
# I have no idea how to start it otherwise...
mount = /=run:app

# nginx needs to be part of whichever group owns this file (ex: 'spano')
chmod-socket = 770
socket = /run/spano/spano.sock
logto = /usr/share/webapps/spano/logs/uwsgi.log
plugins = python3
