server {
	listen 80;
	listen 443 ssl;

	server_name rss.example.net;

        ssl_trusted_certificate /path/to/ca.cer;
        ssl_certificate_key /path/to/cert.key;
        ssl_certificate /path/to/fullchain.cer;

	access_log /var/log/freshrss/access.log;
	error_log /var/log/freshrss/error.log;

	root /usr/share/webapps/FreshRSS/p;

	index index.php index.html;

	location ~ \.php(/.*)?$ {
		fastcgi_pass unix:/run/freshrss/fastcgi.sock;
		fastcgi_split_path_info ^(.+\.php)(/.*)$;
		set $path_info $fastcgi_path_info;
		fastcgi_param PATH_INFO $path_info;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param SCRIPT_NAME     $fastcgi_script_name;
	}

	location / {
		try_files $uri $uri/ index.php;
	}
}

